### ISSUE TITLE
Problem with Irotoridori no sekai

### ISSUE THREAD

**Issue by Arata12** [xmoeproject/FVPLoader#2]
Hi, when I drag the game executable the following error appears

![image](https://user-images.githubusercontent.com/34563333/34324121-be878cac-e822-11e7-85f1-031a2bb3203e.png)

**Comment by xmoezzz** [comment]
Ensure your game path only contain English characters.

2017年12月24日(日) 11:50 Ryusei1 <notifications@github.com>:
