### ISSUE TITLE
where is my.h ?

### ISSUE THREAD

**Issue by Gezine** [xmoeproject/FVPLoader#3]
I can't compile because there is no my.h

**Comment by xmoezzz** [comment]
working in progress

**Comment by Gezine** [comment]
Thanks!

2020년 1월 29일 (수) 오후 4:56, xmoeproject <notifications@github.com>님이 작성:

**Comment by xmoezzz** [comment]
solved (ver 7.0-re)
https://github.com/xmoeproject/FVPLoader/commit/60456278896b19214a4747ea6f67935987e8f451
